/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parkingsystem;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Random;

/**
 *
 * @author Mitsu
 */
public class FullSlotTicket extends javax.swing.JFrame {

    /**
     * Creates new form FullSlotTicket
     */
    public FullSlotTicket() {
        initComponents();
        
         // Get current date and time once
     // Get current date and time once
        Date now = new Date();

        // Date format
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date.setText(" " + df.format(now));

        // Time format
        SimpleDateFormat tf = new SimpleDateFormat("hh:mm:ss a");
        Time.setText(" " + tf.format(now));
        
        
        Random rand = new Random();
        int ticketCode = 1000 + rand.nextInt(9000); // ensures 4 digits (1000–9999)
    
// Example: set it on a JLabel (you need a JLabel named TicketCode in your form)
        TicketNumber.setText("" + ticketCode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        TicketNumber = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(50, 50, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 740, 380, 90));

        TicketNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(TicketNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 190, 50));

        Date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Date.setText("jLabel2");
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 230, 30));

        Time.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Time.setText("jLabel3");
        getContentPane().add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mitsu\\OneDrive\\Documents\\NetBeansProjects\\ParkingQueuing\\src\\MAIN_UI\\FULLSLOT_TICKET.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        WaitQueue wq = new WaitQueue();
        wq.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FullSlotTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FullSlotTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FullSlotTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FullSlotTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FullSlotTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel TicketNumber;
    private javax.swing.JLabel Time;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
