/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parkingsystem;

/**
 *
 * @author Airi
 */
public class P02_IN_OUT extends javax.swing.JFrame {

    /**
     * Creates new form IN_OUT
     */
    public P02_IN_OUT() {
        initComponents();
    SlotServedNumber.setOpaque(false); 
    SlotServedNumber.setBorder(null); 
    SlotServedNumber.setBackground(new java.awt.Color(0, 0, 0, 0));
    SlotServedNumber.setForeground(new java.awt.Color(0, 0, 0));
    SlotServedNumber.setEditable(false); 
    SlotServedNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER); 
    SlotServedNumber.setText(String.valueOf(DATABASE.SlotServed.getCount())); 


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        out = new javax.swing.JButton();
        in = new javax.swing.JButton();
        SlotServedNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(50, 50, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        out.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        out.setContentAreaFilled(false);
        out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outActionPerformed(evt);
            }
        });
        getContentPane().add(out, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 370, 450, 110));

        in.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        in.setContentAreaFilled(false);
        in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inActionPerformed(evt);
            }
        });
        getContentPane().add(in, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, 450, 110));

        SlotServedNumber.setFont(new java.awt.Font("Arial", 1, 55)); // NOI18N
        SlotServedNumber.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SlotServedNumber.setCaretColor(new java.awt.Color(255, 255, 255));
        SlotServedNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlotServedNumberActionPerformed(evt);
            }
        });
        getContentPane().add(SlotServedNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 640, 210, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MAIN_UI/IN&OUT_FNL.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outActionPerformed
    this.setVisible(false);
    P16_OUT outframe = new P16_OUT();
    outframe.setVisible(true);
    }//GEN-LAST:event_outActionPerformed

    private void inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inActionPerformed
     DATABASE.SlotServed.incrementCount();
    SlotServedNumber.setText(String.valueOf(DATABASE.SlotServed.getCount()));
    this.setVisible(false);
    P03_SELECTPARK selectParkFrame = new P03_SELECTPARK();
    selectParkFrame.setVisible(true);
    }//GEN-LAST:event_inActionPerformed

    private void SlotServedNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlotServedNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SlotServedNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P02_IN_OUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P02_IN_OUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P02_IN_OUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P02_IN_OUT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P02_IN_OUT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SlotServedNumber;
    private javax.swing.JButton in;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton out;
    // End of variables declaration//GEN-END:variables
}
