/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parkingsystem;

/**
 *
 * @author Airi
 */
public class P03_SELECTPARK extends javax.swing.JFrame {

    /**
     * Creates new form SELECTPARK
     */
    public P03_SELECTPARK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        R02 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        R03 = new javax.swing.JButton();
        R04 = new javax.swing.JButton();
        R05 = new javax.swing.JButton();
        L01 = new javax.swing.JButton();
        L02 = new javax.swing.JButton();
        L03 = new javax.swing.JButton();
        L04 = new javax.swing.JButton();
        L05 = new javax.swing.JButton();
        R01 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        mainIMG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(50, 50, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 311, 100, 20));

        R02.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        R02.setContentAreaFilled(false);
        R02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R02ActionPerformed(evt);
            }
        });
        getContentPane().add(R02, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 100, 80));

        back.setToolTipText("");
        back.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 120, 120));

        R03.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        R03.setContentAreaFilled(false);
        R03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R03ActionPerformed(evt);
            }
        });
        getContentPane().add(R03, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 100, 80));

        R04.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        R04.setContentAreaFilled(false);
        R04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R04ActionPerformed(evt);
            }
        });
        getContentPane().add(R04, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, 100, 80));

        R05.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        R05.setContentAreaFilled(false);
        R05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R05ActionPerformed(evt);
            }
        });
        getContentPane().add(R05, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 340, 100, 80));

        L01.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        L01.setContentAreaFilled(false);
        L01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L01ActionPerformed(evt);
            }
        });
        getContentPane().add(L01, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, 100, 80));

        L02.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        L02.setContentAreaFilled(false);
        L02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L02ActionPerformed(evt);
            }
        });
        getContentPane().add(L02, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 100, 80));

        L03.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        L03.setContentAreaFilled(false);
        L03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L03ActionPerformed(evt);
            }
        });
        getContentPane().add(L03, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, 100, 80));

        L04.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        L04.setContentAreaFilled(false);
        L04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L04ActionPerformed(evt);
            }
        });
        getContentPane().add(L04, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, 100, 80));

        L05.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        L05.setContentAreaFilled(false);
        L05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L05ActionPerformed(evt);
            }
        });
        getContentPane().add(L05, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 600, 100, 80));

        R01.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        R01.setContentAreaFilled(false);
        R01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R01ActionPerformed(evt);
            }
        });
        getContentPane().add(R01, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 100, 80));

        jLabel4.setText("jLabel3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 308, 100, 20));

        mainIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MAIN_UI/IN_FNL.png"))); // NOI18N
        getContentPane().add(mainIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void L01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L01ActionPerformed
        P04_ENTER_PLATENUMBER P04 = new P04_ENTER_PLATENUMBER();
       P04.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_L01ActionPerformed

    private void R01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R01ActionPerformed
       P04_ENTER_PLATENUMBER P04 = new P04_ENTER_PLATENUMBER();
       P04.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_R01ActionPerformed

    private void R02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R02ActionPerformed
        P04_ENTER_PLATENUMBER P04 = new P04_ENTER_PLATENUMBER();
       P04.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_R02ActionPerformed

    private void R03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R03ActionPerformed
        P04_ENTER_PLATENUMBER P04 = new P04_ENTER_PLATENUMBER();
       P04.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_R03ActionPerformed

    private void R04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R04ActionPerformed
       P04_ENTER_PLATENUMBER P04 = new P04_ENTER_PLATENUMBER();
       P04.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_R04ActionPerformed

    private void R05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R05ActionPerformed
       P04_ENTER_PLATENUMBER P04 = new P04_ENTER_PLATENUMBER();
       P04.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_R05ActionPerformed

    private void L02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L02ActionPerformed
       P04_ENTER_PLATENUMBER P04 = new P04_ENTER_PLATENUMBER();
       P04.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_L02ActionPerformed

    private void L03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L03ActionPerformed
       P04_ENTER_PLATENUMBER P04 = new P04_ENTER_PLATENUMBER();
       P04.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_L03ActionPerformed

    private void L04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L04ActionPerformed
        P04_ENTER_PLATENUMBER P04 = new P04_ENTER_PLATENUMBER();
       P04.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_L04ActionPerformed

    private void L05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L05ActionPerformed
        P04_ENTER_PLATENUMBER P04 = new P04_ENTER_PLATENUMBER();
       P04.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_L05ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        P02_IN_OUT P02 = new P02_IN_OUT();
        P02.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P03_SELECTPARK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P03_SELECTPARK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P03_SELECTPARK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P03_SELECTPARK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P03_SELECTPARK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton L01;
    private javax.swing.JButton L02;
    private javax.swing.JButton L03;
    private javax.swing.JButton L04;
    private javax.swing.JButton L05;
    private javax.swing.JButton R01;
    private javax.swing.JButton R02;
    private javax.swing.JButton R03;
    private javax.swing.JButton R04;
    private javax.swing.JButton R05;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel mainIMG;
    // End of variables declaration//GEN-END:variables
}
